services:
  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: "passbolt"
      MYSQL_USER: "passbolt"
      MYSQL_PASSWORD: "P4ssb0lt"
    volumes:
      - database_volume:/var/lib/mysql

  mailpit:
    image: axllent/mailpit
    container_name: ${MAILPIT_CONTAINER_NAME}
    restart: unless-stopped
    volumes:
      - mailpit_data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
      MP_SMTP_BIND_ADDR: "0.0.0.0:1025"
      MP_SMTP_HOSTNAME: mailpit.local
    hostname: mailpit.local

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.3
    container_name: keycloak
    restart: unless-stopped
    environment:
      # Development credentials
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # Development settings
      KC_HOSTNAME: keycloak.local
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/server.crt.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/server.key.pem
    command: 
      - start-dev
      - --features admin-fine-grained-authz
    ports:
      - 8081:8080
      - 8787:8787
      - 8443:8443
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keys/domain.crt:/opt/keycloak/conf/server.crt.pem
      - ./keys/domain.key:/opt/keycloak/conf/server.key.pem
    networks:
      default:
        aliases:
          - keycloak.local

  passbolt:
    build:
      context: .
      dockerfile: Dockerfile.passbolt
    image: passbolt/passbolt:latest-pro
    restart: unless-stopped
    depends_on:
      - db
      - keycloak
    environment:
      APP_FULL_BASE_URL: https://passbolt.local
      DATASOURCES_DEFAULT_HOST: "db"
      DATASOURCES_DEFAULT_USERNAME: "passbolt"
      DATASOURCES_DEFAULT_PASSWORD: "P4ssb0lt"
      DATASOURCES_DEFAULT_DATABASE: "passbolt"
      EMAIL_TRANSPORT_DEFAULT_HOST: "mailpit"
      EMAIL_TRANSPORT_DEFAULT_PORT: 1025 
      EMAIL_TRANSPORT_DEFAULT_USERNAME: ""
      EMAIL_TRANSPORT_DEFAULT_PASSWORD: ""
      EMAIL_DEFAULT_FROM: "admin@passbolt.com"
      # OIDC configuration for Keycloak
      PASSBOLT_PLUGINS_SSO_PROVIDER_OAUTH2_ENABLED: "true"
      OIDC_ENABLED: "true"
      OIDC_ISSUER: "http://keycloak.local:8443/realms/master"
      OIDC_CLIENT_ID: "passbolt-client"
      OIDC_CLIENT_SECRET: "your-secret-here"
      OIDC_SCOPES: "openid profile email"
      OIDC_VERIFY_SSL: "false"
    volumes:
      - gpg_volume:/etc/passbolt/gpg
      - jwt_volume:/etc/passbolt/jwt
      - ./php-fpm/www.conf:/etc/php-fpm.d/www.conf
    command:
      - /bin/bash
      - -c
      - |
        /usr/bin/wait-for.sh -t 0 db:3306 -- /docker-entrypoint.sh
    ports:
      - 80:80
      - 443:443
      - 9000:9000

  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap
    restart: unless-stopped
    environment:
      LDAP_ORGANISATION: "Passbolt"
      LDAP_DOMAIN: "passbolt.local"
      LDAP_ADMIN_PASSWORD: "P4ssb0lt"
      LDAP_CONFIG_PASSWORD: "P4ssb0lt"
      LDAP_READONLY_USER: "true"
      LDAP_READONLY_USER_USERNAME: "readonly"
      LDAP_READONLY_USER_PASSWORD: "readonly"
      LDAP_TLS: "true"
      LDAP_TLS_VERIFY_CLIENT: "never"
      LDAP_TLS_CIPHER_SUITE: "SECURE256"
      LDAP_TLS_PROTOCOL_MIN: "3.1"
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
      - ./keys/domain.crt:/container/service/slapd/assets/certs/ldap.crt
      - ./keys/domain.key:/container/service/slapd/assets/certs/ldap.key
    networks:
      default:
        aliases:
          - ldap.local

volumes:
  database_volume:
  gpg_volume:
  jwt_volume:
  keycloak_data:
  mailpit_data:
  ldap_data:
  ldap_config:
