FROM passbolt/passbolt:latest-pro

# Copy your CA certificate into the appropriate directory
COPY keys/ca.crt /usr/local/share/ca-certificates/keycloak.crt
# Update the CA trust store
RUN update-ca-certificates
