http:
  serversTransports:
    passbolt-transport:
      insecureSkipVerify: true

tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
  certificates:
    - certFile: /certs/passbolt.crt
      keyFile: /certs/passbolt.key
    - certFile: /certs/keycloak.crt
      keyFile: /certs/keycloak.key
    - certFile: /certs/smtp.crt
      keyFile: /certs/smtp.key
    - certFile: /certs/traefik.crt
      keyFile: /certs/traefik.key

